const Locators = {
 userNameInput: "//*[@id='username']",
 password: "//*[@id='password']",
 signInButton: "//*[@id='kc-login']",
 headerText: "//span[@role='link' and @aria-current='page']",
 residentLink: "a:has-text('Cliëntenbeheer')",
 residentNameColumn: "//button[.//span[normalize-space(text())='Name']]",
 residentSectorColumn: "//button[.//span[normalize-space(text())='Sector']]",
 tableBeforeHeadersXpath: "//table//thead//tr//th[",
 tableAfterHeadersXpath: "]//div//button[1]//span//span",
 tableRowBeforeXpath: "//table//tbody//tr",
 tableRowAferXpath: "//td[1]//span",
 tableHeaders: "//table//thead//tr//th//span//span",
 tableRow: "//table//tbody//tr",
 tableBeforeDelBtn: "//table//tbody//tr",
 tableBtwDelBtn: "//td",
 tableAfterDelBtn:"//div//div//button[2]",
 arrowUpDownXpath: "//div[contains(@class,'flex flex-col ml-1')]",
 tableColumnCount: "//table//thead//tr//th",
 firstCellText: "//table//tbody//tr[1]//td[1]//span",
 sectorFirstCellText: "//table//tbody//tr[1]//td[2]//span",
 roomFirstCellText: "//table//tbody//tr[1]//td[3]//span",
 typeFirstCellText: "//table//tbody//tr[1]//td[1]//span",
 creationDateFirstCellText: "//table//tbody//tr[1]//td[2]//span",
 residentFirstCellText: "//table//tbody//tr[1]//td[4]//span",
 sectorFirstCellInAlarmOverview: "//table//tbody//tr[1]//td[5]//span",
 processorFirstCellText: "//table//tbody//tr[1]//td[6]//span",
 polygonBtn: "button:has(svg polygon)",
 polygondropdownOptions: "[cmdk-item]",
 residentColumns: "//button[starts-with(@id, 'radix-_r_') and @type='button']",
 columnBtnXpath: "//button[text()='Kolommen']",
 clientNumberColumnXpath: "//div[span[text()='Klantnummer']]",
 addressColumnXpath: "//div[span[text()='Address']]",
 privacyModeXpath: "//div[span[text()='Privacy Mode']]",
 activeFiltersXpath: "//div[span[text()='Actieve filters']]",
 resetVisibilityButton: "//button[text()='Zichtbaarheid resetten']",
 resetFiltersXpath:"//button[text()='Filters resetten']",
 lastModifiedXpath: "//div[span[text()='Laatst gewijzigd']]",
 locationXpath: "//div[span[text()='Locatie']]",
 escalatedXpath: "//div[span[text()='Geëscaleerd']]",
 sectorXpath: "//div[span[text()='Zorgsectie']]",
 totalDelayXpath: "//div[span[text()='Totale doorlooptijd']]",
 step1Xpath: "//div[span[text()='➛ Stap 1']]",
 step2Xpath: "//div[span[text()='➛ Stap 2']]",
 editButtonXpath: "//button[@title='Bewerken']",
 editBoxHeaderXpath: "//h2[text()='Cliënt bewerken']",
 formlabelCSS: "#resourceForm label",
 nameDataForm: "//input[@name='name']",
 clientNumberDataForm: "//input[@name='externalId']",
 streetDataForm: "//input[@name='street']",
 houseNumberDataForm: "//input[@name='number']",
 postalCodeDataForm: "//input[@name='postalCode']",
 cityDataForm: "//input[@name='city']",
 telephoneNumberData : "//input[@name='phoneNumber']",
 saveButton: "//button[text()='Opslaan']",
 deleteButtonXpath: "button[title='Verwijderen']",
 toDeleteBtnXpath: "//button[text()='Verwijderen']",
 alarmOverviewXpath: "//span[text()='Alarmoverzicht']",
 closeButton: "button:has(span:has-text('Close'))",
 closeBtnEscalate: "//button[.//span[text()='Close']]",
 paginationRightXpath: "//*[local-name()='svg' and @class='lucide lucide-chevron-right']",
 paginationLeftXpath: "//*[local-name()='svg' and @class='lucide lucide-chevron-left']",
 tabledataXpath: "//table//tbody//tr//td[1]",
 refreshToggleXpath: "//*[local-name()='svg' and @class='lucide lucide-toggle-left text-white']",
 refreshToggleAfterEnabled: "//*[local-name()='svg' and @class='lucide lucide-toggle-right text-white']",
 openAlarmXpath: "span.bg-failure",
 alarmTooltipXpath: "span:has-text('open')",
 statusComboboxXpath: "button[role='combobox']",
 fromDateButtonXpath: "//label[normalize-space(.)='Van:']/following-sibling::button",
 toDateButtonXpath: "//label[normalize-space(.)='Tot:']/following-sibling::button",
 previousMonthButtonXpath: "//button[@name='previous-month']",
 nextButtonXpath: "//button[@name='next-month']",
 monthLabelXpath: "//div[contains(@id,'react-day-picker')]",
 fromDateValueXpath: "//button[normalize-space(text())='10']",
 toDateValueXpath: "//button[normalize-space(text())='3']",
 escalationLaddersXpath : "//span[text()='Escalatieladders']",
 escalationLaddersHeader: "table thead th",
 addEscalationLadderXpath: "button:has-text('Toevoegen')",
 addEscalationLadderHeaderXpath: "//h2[text()='Nieuwe escalatieladder']",
 startSectorLabelXpath: "//label[text()='Start sector']",
 selectStartSectorXpath: "//span[text()='Kies een startsector']",
 selectXpath: "select",
 addStepXpath: "//div[text()='Voeg een nieuwe stap toe']",
 escalationStepsXpath: "//h3[text()='Escalation steps']",
 shiftStep1Xpath: "//label[text()='➛ Dienst stap 1']",
 delayStep1Xpath: "//label[text()='Vertraging stap 1']",
 shiftstepDropdownXpath: "button[role='combobox']",
 stepDelayXpath: "//input[@type='number' and @name='step_1_delay']",
 trashBtnXpath: "div.grid.grid-cols-3 svg.lucide-trash2",
 usersLinkXpath: "//span[text()='Gebruikers']",
 naamUserXpath: "//div[span[text()='Naam']]",
 emailUserXpath: "//div[span[text()='E-mail']]",
 rollenUserXpath: "//div[span[text()='Rollen']]",
 sectorUserXpath: "//div[span[text()='Zorgsectie(s)']]",
 addNewUserXpath: "button:has-text('Toevoegen')",
 formLabelXpath: "form#resourceForm label[data-slot='form-label']",
 emailUsersDataFormXpath: "//input[@name='email']",
 nameUsersDataFormXpath: "//input[@name='displayName']",
 passwordUsersDataFormXpath: "//input[@name='password']",
 confPasswordUsersDataFormXpath: "//input[@name='confirmpassword']",
 phoneNumberUsersDataFormXpath: "//input[@name='phoneNumber']",
 rollenUsersDataFormXpath: "//label[text()='Rollen']/following-sibling::div//input[@placeholder='Zoeken...']",
 sectorUsersDataFormXpath: "//label[text()='Zorgsectie(s)']/following-sibling::div//input[@placeholder='Zoeken...']",
 rollenValueToSelectXpath: "[data-value='Organisatiebeheerder']",
 searchInputBoxXpath: "//input[@type='search']",
 filterResetBtnXpath: "//button[normalize-space()='Filters resetten']"

 
};

export default Locators;